### PR TITLE
Fixed Typos in Docs Pages - Added New Contributor 

### PR DESCRIPTION
**Pull request by lubeskih**
## Description
This PR fixes some typos I managed to come around while reading the `8-Bit Programming` docs. I also added some `<br>`'s where I thought they need to be.

## Motivation and Context
Had to fix some small things (usually typos) in the docs that I found annoying while reading.

## How Has This Been Tested?
I haven't tested this since it's just change of text involved in the docs, no functionality was touched whatsoever.

## Screenshots (if appropriate):
N/A

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit and integration tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I updated the SamVer in the appropriate .csproj file (only for to-master-merges, ask rbaker26 for a release number).

### CODE REVIEW

**Comment by lubeskih** [comment]
Hello. I'm not sure if I filled the PR template as I should, so make sure to check that as well. You probably have to add another item in the checklist when it comes to documentation improvements.

**Comment by rbaker26** [comment]
@lubeskih 
Just saw your email. 
Sorry, I think I misinterpreted what you were asking in the email. 
I will take a look at this when I get home.

**Comment by rbaker26** [comment]
commit 42366e714e8ae36d37ec3813586a0c8a1646c915
fixed merge conflict between branches

**Comment by rbaker26** [comment]
The Benchmark Results GH Action is failing bc it is running in the Authors repo
This is not an issue.

**Review by rbaker26 — CHANGES_REQUESTED** [review]
Please update the following file:
`SAP1EMU\SAP1EMU.GUI\Views\Home\Contributors.cshtml`
In-between lines 18 and 19 

This will add your github profile card.
See https://sap1emu.net/Home/Contributors

**Review by rbaker26 — APPROVED** [review]
everything looks good

**Pull request merged**
